### ISSUE TITLE
got an error when i run npm start

### ISSUE THREAD

**Issue by azl397985856** [yalishizhude/api-mock#2]
firstly, i run npm install , then run npm start . at that time,  an error ouccored.
here the stack trace is.
[2016-04-29 12:45:15.367] [ERROR] console - [Error: failed to connect to [127.0.0.1:27017]]
Error: failed to connect to [127.0.0.1:27017]
    at null.<anonymous> (E:\github\api-document\node_modules\mongodb\lib\mongodb\connection\server.js:556:25)
    at emitThree (events.js:97:13)
    at emit (events.js:175:7)
    at null.<anonymous> (E:\github\api-document\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:156:15)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (E:\github\api-document\node_modules\mongodb\lib\mongodb\connection\connection.js:534:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)

what should i do?

**Comment by yalishizhude** [comment]
Maybe you forgot to start mongodb first~

**Comment by azl397985856** [comment]
i forgot to say that what operate system i'm using is win7 .  so a pack should be installed first .
install the win7 pack and restart my computer, it works
